### ISSUE TITLE
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sparqlQueryController' defined in URL 

### ISSUE THREAD

**Issue by nikhilg1312** [ontop/ontop-tutorial#2]
This more of doubt than a issue.I am new user of ontop and was exploring it.
I followed the steps in https://github.com/ontop/ontop-tutorial/blob/master/endpoint/endpoint-docker.md

I ensured that h2 database is running by querying it.Later the ran the docker run command(linux).

I am getting following error :

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sparqlQueryController' defined in URL [jar:file:/opt/ontop/lib/ontop-endpoint-3.0.0.jar!/it/unibz/inf/ontop/endpoint/SparqlQueryController.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [it.unibz.inf.ontop.endpoint.SparqlQueryController]: Constructor threw exception; nested exception is org.eclipse.rdf4j.repository.RepositoryException: it.unibz.inf.ontop.exception.DBMetadataExtractionException: Connection is broken: "java.net.UnknownHostException: host.docker.internal: host.docker.internal" [90067-196]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:304) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:285) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1308) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1154) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]

Am I missing something obvious? Thanks in advnace

**Comment by ghxiao** [comment]
Hi, I forgot to note that Linux users have to modify the property jdbc.url in the file university-complete.docker.properties. Replace host.docker.internal with the IP address of your machine. 

I have updated the instruction according.

See: https://github.com/docker/libnetwork/pull/2348

**Comment by nikhilg1312** [comment]
I added my Private ip address by command ` hostname - I` and entered the Ip address in the file university-complete.docker.properties replacing` host.docker.internal `.

Now I am getting following error :

```

Failed to instantiate [it.unibz.inf.ontop.endpoint.SparqlQueryController]: Constructor threw exception; nested exception is org.eclipse.rdf4j.repository.RepositoryException: it.unibz.inf.ontop.exception.DBMetadataExtractionException: Connection is broken: "java.net.ConnectException: Connection refused (Connection refused): 127.0.1.1" [90067-196]
2019-09-03 10:02:17.113  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2019-09-03 10:02:17.191  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-09-03 10:02:17.209 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sparqlQueryController' defined in URL [jar:file:/opt/ontop/lib/ontop-endpoint-3.0.0.jar!/it/unibz/inf/ontop/endpoint/SparqlQueryController.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [it.unibz.inf.ontop.endpoint.SparqlQueryController]: Constructor threw exception; nested exception is org.eclipse.rdf4j.repository.RepositoryException: it.unibz.inf.ontop.exception.DBMetadataExtractionException: Connection is broken: "java.net.ConnectException: Connection refused (Connection refused): 127.0.1.1" [90067-196]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:304) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:285) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1308) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1154) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.3.RELEASE.jar:5.1.3.RELEASE]

```


is this normal? I guess DNS is not happening

**Comment by ghxiao** [comment]
From the error message: `Connection refused (Connection refused): 127.0.1.1`, it seems that you are using 127.0.0.1 as the IP. You cannot use 127.0.0.0, because it points to the docker image itself. 

You can run `ifconfig` to find other IP addresses. In my case, it is in the device `en0`.

**Comment by nikhilg1312** [comment]
I got my ip address in` wlp2s0: `.
But now I am getting the following error :

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sparqlQueryController' defined in URL [jar:file:/opt/ontop/lib/ontop-endpoint-3.0.0.jar!/it/unibz/inf/ontop/endpoint/SparqlQueryController.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [it.unibz.inf.ontop.endpoint.SparqlQueryController]: Constructor threw exception; nested exception is org.eclipse.rdf4j.repository.RepositoryException: it.unibz.inf.ontop.exception.DBMetadataExtractionException: Remote connections to this server are not allowed, see -tcpAllowOthers [90117-196]
`

**Comment by ghxiao** [comment]
It seems that the h2 server is not accessible from outside. You may need to configure your firewall.

A better way for the tutorial is to put h2 into another docker image, and use docker-compose, but I don't have time to write it down for the moment.
