### ISSUE TITLE
how to solve the error

### ISSUE THREAD

**Issue by northeasternLiu** [ontop/ontop-tutorial#4]
when I run "Reasoner"->"start reasoner"，show the error
 ERROR  11:19:55  An error occurred during reasoning: null.
java.lang.NullPointerException: null
	at it.unibz.inf.ontop.protege.core.OntopReasonerInfo.getConfiguration(OntopReasonerInfo.java:50) ~[na:na]
	at org.protege.editor.owl.model.inference.ReasonerUtilities.createReasoner(ReasonerUtilities.java:17) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.ensureRunningReasonerInitialized(OWLReasonerManagerImpl.java:428) ~[na:na]
	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.run(OWLReasonerManagerImpl.java:386) ~[na:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
![image](https://user-images.githubusercontent.com/13679320/66797667-1f152100-ef3e-11e9-9aef-80fb024ff75c.png)
![image](https://user-images.githubusercontent.com/13679320/66797681-30f6c400-ef3e-11e9-9636-3072eaab68e9.png)

**Comment by ghxiao** [comment]
Hi, 

This is likely a known problem of Protege configuration. Protege uses a global configuration file. If you upgrade the version of protege or ontop plugin, there is a good chance the stored configuration becomes invalid, and you see a cryptic error message like what you have. To solve it, you need to "reset preferences" in the preferences window. Unfortunately, as far as we understood, this is a problem of the protege framework itself and users have to do the manual reset.

Moreover, having multi-version of protege can cause the same issue. So in general, we recommend using only the latest version (5.5 now) of protege on one machine.

Regards,

Guohui

Ref: https://groups.google.com/forum/#!topic/ontop4obda/q0_PgqfY9aM

**Comment by JohannesLipp** [comment]
Hey there,
I experienced the same problem and solved it by downloading the ontop-protege-bundle from Sourceforge and copy&replace all jar-files in `Protege-5.5.0\bundles\` from the zip-file to the respective Protege dir.
